### ISSUE TITLE
Erreur De Reaction

### ISSUE THREAD

**Issue by ViTraX** [Acenox/Ticket#2]
Dans ton code tu mes 

`    discord name of event-emote = "x":
        if discord name of event-channel contains "Ticket-":
            remove 1 from {ticket}
            updategame("update")
            delete discord entity event-channel`

Dans ce cas quand le bot vas mettre la reaction le salon sera delete 

Pareil quand il vas ajouté la reaction du cochement de case pour créer un channel la reaction sera delete donc personne pourra ouvrir de ticket à reglé

**Comment by JorisPV** [comment]
Salut,

Merci du signalement, j'avais déjà corrigé l'erreur en local, mais j'ai oublié de le fixer sur la version public.
Je push ça 👍 

Cordialement,
